export interface Expenses {
    id: number,
    user_id: number,
    category_id: number,
    description: string,
    date: string,
    amount: number,
}

export const expensesData: Expenses[] = [
    {
        id: 1,
        user_id: 1,
        category_id: 2,
        description: "Trader Joe's",
        date: "05-20-2024",
        amount: 50.75,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 2,
        description: "Whole Foods",
        date: "05-10-2024",
        amount: 103.99,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 3,
        description: "Taco Bell",
        date: "05-04-2024",
        amount: 12.50,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 3,
        description: "Cheesecake Factory",
        date: "05-14-2024",
        amount: 112.30,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 4,
        description: "Rent",
        date: "05-01-2024",
        amount: 2500,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 5,
        description: "Phone",
        date: "05-01-2024",
        amount: 200,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 5,
        description: "Gas",
        date: "05-01-2024",
        amount: 20,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 5,
        description: "Electricity",
        date: "05-01-2024",
        amount: 200,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 5,
        description: "Internet",
        date: "05-01-2024",
        amount: 80,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 7,
        description: "Gas",
        date: "05-01-2024",
        amount: 30.01,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 7,
        description: "Gas",
        date: "05-15-2024",
        amount: 42.60,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 7,
        description: "Gas",
        date: "05-25-2024",
        amount: 33.33,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 8,
        description: "Car Payment",
        date: "05-01-2024",
        amount: 400,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 9,
        description: "Jacket",
        date: "05-27-2024",
        amount: 80,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 9,
        description: "Shoes",
        date: "05-27-2024",
        amount: 50,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 10,
        description: "Netflix",
        date: "05-01-2024",
        amount: 20,
    },
    {
        id: 1,
        user_id: 1,
        category_id: 10,
        description: "Spotify",
        date: "05-01-2024",
        amount: 20,
    },
]